services:
    php:
        build:
            dockerfile: .docker/dev/Dockerfile
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
                USER_NAME: ${USER_NAME:-illumineer}
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "9501:9501"
